/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2016-07-08 17:28:43 UTC)
 * on 2016-08-29 at 14:43:27 UTC 
 * Modify at your own risk.
 */

package com.example.recipebackend.recipesendpoint.model;

/**
 * Model definition for Ingrrecipe.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the recipesendpoint. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Ingrrecipe extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("id_ing")
  private java.lang.String idIng;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("id_ingrrecipe")
  private java.lang.String idIngrrecipe;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Key key;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String measurementu;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String quantity;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getIdIng() {
    return idIng;
  }

  /**
   * @param idIng idIng or {@code null} for none
   */
  public Ingrrecipe setIdIng(java.lang.String idIng) {
    this.idIng = idIng;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getIdIngrrecipe() {
    return idIngrrecipe;
  }

  /**
   * @param idIngrrecipe idIngrrecipe or {@code null} for none
   */
  public Ingrrecipe setIdIngrrecipe(java.lang.String idIngrrecipe) {
    this.idIngrrecipe = idIngrrecipe;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Key getKey() {
    return key;
  }

  /**
   * @param key key or {@code null} for none
   */
  public Ingrrecipe setKey(Key key) {
    this.key = key;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getMeasurementu() {
    return measurementu;
  }

  /**
   * @param measurementu measurementu or {@code null} for none
   */
  public Ingrrecipe setMeasurementu(java.lang.String measurementu) {
    this.measurementu = measurementu;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getQuantity() {
    return quantity;
  }

  /**
   * @param quantity quantity or {@code null} for none
   */
  public Ingrrecipe setQuantity(java.lang.String quantity) {
    this.quantity = quantity;
    return this;
  }

  @Override
  public Ingrrecipe set(String fieldName, Object value) {
    return (Ingrrecipe) super.set(fieldName, value);
  }

  @Override
  public Ingrrecipe clone() {
    return (Ingrrecipe) super.clone();
  }

}
