/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2016-04-08 17:16:44 UTC)
 * on 2016-04-18 at 10:32:29 UTC 
 * Modify at your own risk.
 */

package com.example.carlo.recetapp.recipesendpoint.model;

/**
 * Model definition for CardInfo.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the recipesendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class CardInfo extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String name;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String summary;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String type;

  /**
   * @return value or {@code null} for none
   */
  public String getName() {
    return name;
  }

  /**
   * @param name name or {@code null} for none
   */
  public CardInfo setName(String name) {
    this.name = name;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getSummary() {
    return summary;
  }

  /**
   * @param summary summary or {@code null} for none
   */
  public CardInfo setSummary(String summary) {
    this.summary = summary;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getType() {
    return type;
  }

  /**
   * @param type type or {@code null} for none
   */
  public CardInfo setType(String type) {
    this.type = type;
    return this;
  }

  @Override
  public CardInfo set(String fieldName, Object value) {
    return (CardInfo) super.set(fieldName, value);
  }

  @Override
  public CardInfo clone() {
    return (CardInfo) super.clone();
  }

}
