/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2016-04-08 17:16:44 UTC)
 * on 2016-04-18 at 10:32:29 UTC 
 * Modify at your own risk.
 */

package com.example.carlo.recetapp.recipesendpoint.model;

/**
 * Model definition for Email.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the recipesendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Email extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String email;

  /**
   * @return value or {@code null} for none
   */
  public String getEmail() {
    return email;
  }

  /**
   * @param email email or {@code null} for none
   */
  public Email setEmail(String email) {
    this.email = email;
    return this;
  }

  @Override
  public Email set(String fieldName, Object value) {
    return (Email) super.set(fieldName, value);
  }

  @Override
  public Email clone() {
    return (Email) super.clone();
  }

}
